#Crie um programa e Python em que as quatro operações em que todos os resultados resultam em 8.
num1 = int(input("Digite aqui um número:"))
num2 = int(input("Digite aqui um número:"))
num3 = int(input("Digite aqui um número:"))
num4 = int(input("Digite aqui um número:"))
num5 = int(input("Digite aqui um número:"))
soma = (num1 + num2)
print(soma, "observa-se que o resultado é 8")
sub = (num3 - num1)
print(sub, "observa-se que o resultado é 8")
multi = (num4 * num1)
print(multi, "observa-se que o resultado é 8")
div = (num5 / num1)
print(div, "observa-se que o resultado é 8")